on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-devenv:
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: SimenB/github-actions-cpu-cores@97ba232459a8e02ff6121db9362b09661c875ab8  # v2.0.0
        id: cpucores
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: metadev
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          images: ghcr.io/${{ github.repository_owner }}/ps1linux-devenv
          tags: |
            type=sha,format=short,prefix=r
      - uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          platforms: linux/386
          build-args: NCPU=${{ steps.cpucores.outputs.count }}
          push: true
          tags: ${{ steps.metadev.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: metarel
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          images: ghcr.io/${{ github.repository_owner }}/ps1linux-devenv
          tags: |
            type=raw,value=latest
            type=ref,event=tag
      - uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          platforms: linux/386
          build-args: NCPU=${{ steps.cpucores.outputs.count }}
          push: true
          tags: ${{ steps.metarel.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-ps1linux:
    runs-on: ubuntu-24.04
    needs: build-devenv
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          cid=$(docker run --rm -d -i -v $PWD:/work -w /work ghcr.io/${{ github.repository_owner }}/ps1linux-devenv)
          docker exec $cid cp vendors/Sony/PlayStation1/config.uclinux .config
          docker exec $cid make oldconfig
          docker exec $cid make dep
          docker exec $cid make
          docker stop -t 0 $cid
      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            images/kernel.exe
            images/output.mcd
            images/kernel.sym
